language: racket
sudo: false

env:
  global:
    - RACKET_VERSION=7.0
    - RACKET_DIR=~/racket

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script:
 - raco test tests.rkt
